name: "PNPM install"
description: "Setup pnpm cache and install dependencies"

inputs:
  node-version:
    description: "The node version to setup"
    required: true
  pnpm-version:
    description: "The pnpm version to setup"
    required: true

runs:
  using: "composite"

  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install pnpm ${{ inputs.pnpm-version }}
      uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: false

    - name: Expose pnpm config through "$GITHUB_OUTPUT"
      id: pnpm-config
      shell: bash
      run: |
        echo "PNPM_STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-config.outputs.PNPM_STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --prefer-offline